version: '3.5'
services:
  api:
    build: ./api
    ports:
      - '8057:8057'
    environment:
      ALIAS: '/'
      PORT: '8057'
      JWT_SECRET: $JWT_SECRET
      SNOWFLAKE_NODE: $SNOWFLAKE_NODE
    depends_on:
      - db
    restart: always
    networks:
      - backend
  db:
    build: ./db
    expose:
        - '3306'
    volumes:
        - db:/var/lib/mysql
    environment:
        MYSQL_ROOT_PASSWORD: 'password'
    restart: always
    networks:
      - backend
volumes:
  db:

networks:
  backend: